### ISSUE TITLE
C5

### ISSUE THREAD

**Issue by fawadkhanf3** [igrek51/connect4solver#4]
Hi, could you please tell me how to modify the program for C5 on a 9x7 board?

**Comment by igrek51** [comment]
@fawadkhanf3  Hi, It's already supported. You should set the win streak to 5. In general, use the program with the following arguments:
```
./c4solver -win 5 -width 9 -height 7
```

**Comment by igrek51** [comment]
Sorry. Actually, it won't work, but the problem is not with the 5 win streak, but the board size:

> Maximum width is 8 (due to keeping board state in uint64 key)

5 in a row will work with board at most 8x7:

```
./c4solver -win 5 -width 8 -height 7
```

The main obstacle preventing from using larger boards is the Cache (that remembers results for the same board positions). It's here in the code:

https://github.com/igrek51/connect4solver/blob/a9017b9673ebd1752d2b7c751cf9c69d251fca3d/solver/generic_solver/cache.go#L77

It uses uint64 to calculate the "board key" that is used as a key in the positions map.
If you want to use larger boards like 9x7, you might want to disable the cache, but you'll probably get the results much slower.

**Comment by fawadkhanf3** [comment]
so if I use `./c4solver -win 5 -width 9 -height 7 --nocache`, will it do the job? It'll still train and save the best weights, but slower, right?

**Comment by igrek51** [comment]
> so if I use `./c4solver -win 5 -width 9 -height 7 --nocache`, will it do the job? It'll still train and save the best weights, but slower, right?

Yes, it should work. That's the correct way to use it, but bear in mind that it can be extremely slow. This program has been optimised for a 7x6 setup with a 4 win streak and these optimisations have proved to be really game-changing.

**Comment by fawadkhanf3** [comment]
There was an assertion in the code to restrict width to 8, i had to comment it out. And yes, it's extremely slow, the progress is still at 0% after 73 hours. And I'm running it on a good system with GPU (although I'm not sure the code is utilizing GPU or not).
